ALTER TABLE "Invoice" ADD COLUMN "dueAt" TIMESTAMP(3);

UPDATE "Invoice"
SET "dueAt" = "createdAt" + INTERVAL '30 days';

ALTER TABLE "Invoice" ALTER COLUMN "dueAt" SET NOT NULL;

ALTER TABLE "Invoice" ALTER COLUMN "dueAt" SET DEFAULT ((CURRENT_TIMESTAMP AT TIME ZONE 'UTC') + INTERVAL '30 days');
